config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'say/hello'
  get 'say/goodbye'
  root 'categories#index'
  #only for models we can use "resources", which finds all actions for the given controller
  resources :categories
  resources :products
  resources :reviews
  resources :cart_line_items
  resources :addresses
  resources :wishlists
  resources :orders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  # Create, Read, Update, Destroy:
  # :create : new, create
  # :read : index, show
  # :update : edit, update
  # :destroy : destroy
  # :manage : all 7 above actions


  def initialize(user)
    if user.nil?
        can :read, [Category, Product]
    elsif user.role? "admin"
        can :manage, [Category, Product, Review]
    elsif user.role? "moderator"
        can :read, [Category, Product, Review]
        can :create, Review
        can :update, [Category,Product]
        can :destroy, Review
    elsif user.role? "customer"
        can :read, [Category, Product]
        can [:read, :create], Review
        can [:update, :destroy], Review do |review|
            review.user_id == user.id
        end
    end
  end



    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :user
	has_many :orders
	validates_presence_of :name, :pincode, :street, :landmark, :city, :user_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_line_item.rb
class CartLineItem < ApplicationRecord
	belongs_to :product
	belongs_to :user

	validates_presence_of :product_id, :user_id, :quantity

	#slim controller, fat model concept: all methoda should be detailed in the model side, and referenced to on the controller side.
	def save_or_update
		line_item = CartLineItem.find_by(user_id: self.user_id, product_id: self.product_id)
		if line_item.nil?
			self.save
		else
			line_item.update_attributes(quantity: line_item.quantity + self.quantity)
		end
	end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
	validates_presence_of :name
	validates_uniqueness_of :name
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	belongs_to :address
	has_many :order_line_items
	
	before_validation :set_default_values
	after_create :transfer_cartlineitems_to_orderlineitems
	after_create :empty_cartlineitems


	validates_presence_of :order_number, :order_date, :user_id, :total, :address_id

	def set_default_values
		self.order_number = "#{Random.rand(1000)}"
		self.order_date = Date.today
		self.total = calculate_total
	end

	def calculate_total
		total = 0
		self.user.cart_line_items.each do |cart_line_item|
			total += (cart_line_item.product.price * cart_line_item.quantity)
		end
		return total
	end

	def transfer_cartlineitems_to_orderlineitems
		self.user.cart_line_items.each do |cart_line_item|
			OrderLineItem.create(product_id: cart_line_item.product_id, price: cart_line_item.product.price, order_id: self.id, quantity: cart_line_item.quantity)
		end
	end

	def empty_cartlineitems
		# self.user.cart_line_items.each do |cart_line_item|
		# 	cart_line_item.destroy
		# end
		CartLineItem.delete(self.user.cart_line_items)

	end
end

app/models/order_line_item.rb
class OrderLineItem < ApplicationRecord
	belongs_to :order
	belongs_to :product
	validates_presence_of :product_id, :price, :order_id, :quantity
end

app/models/permission.rb
class Permission < ApplicationRecord
	belongs_to :user
	belongs_to :role
end

app/models/product.rb
class Product < ApplicationRecord
has_many :reviews
belongs_to :category

has_many :cart_line_items

has_many :wishlists

has_many :order_line_items


validates_presence_of :name, :price, :description, :category_id, :cod_eligible, :feature_image_url
validates_numericality_of :price, minimum: 100
validates_numericality_of :category_id, greater_than_or_equal_to: 1

end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :product
	belongs_to :user
	
	validates_presence_of :body, :product_id, :rating, :user_id
	validates_length_of :body, within: 10...1000
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :permissions
	has_many :users, through: :permissions

	validates_presence_of :name
	validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
	has_many :reviews

	has_many :permissions
	has_many :roles, through: :permissions

	has_many :cart_line_items

	has_many :addresses

	has_many :wishlists

	has_many :orders

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	validates_presence_of :username, :mobile
	validates_numericality_of :mobile
	validates_length_of :mobile, is: 10

	#whenever a user registers, by default he is a customer:
	#callback:
	after_create :assign_customer_role

	def assign_customer_role
		Permission.create(user_id: self.id, role_id: Role.last.id)
	end

	def role?(role)
		self.roles.pluck(:name).include?(role)
	end
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
	belongs_to :user
	has_many :products, through: :user
	validates_presence_of :product_id, :user_id
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
	before_action :authenticate_user!
	def index 
		@addresses = current_user.addresses
	end

	def new
		@address = Address.new
	end

	def create
		@address = Address.new(params[:address].permit(:name, :pincode, :street, :landmark, :city))
		@address.user_id = current_user.id
		if @address.save
			redirect_to addresses_path, notice: "Address successfully created"
		else
			render action: 'new'
		end
	end

	def edit
		@address = Address.find(params[:id])
	end

	def update
		@address = Address.find(params[:id])
		if @address.update_attributes(params[:address].permit(:name, :pincode, :street, :landmark, :city))		
			redirect_to addresses_path, notice: "Address successfully updated"
		else
			render action: 'edit'
		end
	end

	def destroy
		@address = Address.find(params[:id])
		@address.destroy
		redirect_to addresses_path, notice: "Address successfully deleted"
	end

end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  end

  def goodbye
  	
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/addresses/_form.html.erb
<%= form_for @address, html: {id: 'address_form'} do |f| %>

	<% if @address.errors.any? %>
		<p>Address couldn't be saved due to following errors:</p>
		<ol>
		<% @address.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ol>
	<% end %>
		<label for="name">Name:</label><br/>
		<%= f.text_field :name, placeholder: "Full Name", id: "address_name" %>
		<span id="nameErrorHandle"></span>

		<label for="pincode">Pincode:</label><br/>
		<%= f.text_field :pincode, placeholder: "PIN", id: "address_pin" %>
		<span id="pinErrorHandle"></span>

		<label for="street">Street:</label><br/>
		<%= f.text_area :street, placeholder: "Street", id: "street" %>
		<span id="streetErrorHandle"></span>

		<label for="landmark">Landmark:</label><br/>
		<%= f.text_field :landmark, placeholder: "Landmark", id: "landmark" %>
		<span id="landmarkErrorHandle"></span>

		<label for="city">City:</label><br/>
		<%= f.text_field :city, placeholder: "City", id: "city" %>
		<span id="cityErrorHandle"></span> <br/>

		<%= f.submit "Submit", id: "submit" %>

<% end %>

<script type="text/javascript">
	var numberFormat = /^\d+$/;

	var nameHandle = document.getElementById('address_name');
	var pinHandle = document.getElementById('address_pin');
	var streetHandle = document.getElementById('street');
	var landmarkHandle = document.getElementById('landmark');
	var cityHandle = document.getElementById('city');

	var formHandle = document.getElementById('address_form');
	var submitHandle = document.getElementById('submit');

	var validator = {
		nameValid: false,
		pinValid: false,
		streetValid: false,
		landmarkValid: false,
		cityValid: false
	}

	function nameValidation(){
		if (nameHandle.value === "") {
			validator.nameValid = false;
			nameErrorHandle.innerHTML = "Can't be blank";
		}
		else{
			validator.nameValid = true;
			nameErrorHandle.innerHTML = "";
		}
	}

	function pinValidation(){
		if (pinHandle.value === "") {
			validator.pinValid = false;
			pinErrorHandle.innerHTML = "Can't be blank";
		}
		else if (!numberFormat.test(pinHandle.value)) {
			validator.pinValid = false;
			pinErrorHandle.innerHTML = "Only numbers allowed";
		}
		else if (pinHandle.value !== 6) {
			validator.pinValid = false;
			pinErrorHandle.innerHTML = "should be 6 digits";
		}
		else{
			validator.pinValid = true;
			pinErrorHandle.innerHTML = "";
		}
	}

	function streetValidation(){
		if (streetHandle.value === "") {
			validator.streetValid = false;
			streetErrorHandle.innerHTML = "Can't be blank";
		}
		else{
			validator.streetValid = true;
			streetErrorHandle.innerHTML = "";
		}
	}

	function landmarkValidation(){
		if (landmarkHandle.value === "") {
			validator.landmarkValid = false;
			landmarkErrorHandle.innerHTML = "Can't be blank";
		}
		else{
			validator.landmarkValid = true;
			landmarkErrorHandle.innerHTML = "";
		}
	}

	function cityValidation(){
		if (cityHandle.value === "") {
			validator.cityValid = false;
			cityErrorHandle.innerHTML = "Can't be blank";
		}
		else{
			validator.cityValid = true;
			cityErrorHandle.innerHTML = "";
		}
	}

	formHandle.addEventListener('submit', function(e){
		nameValidation();
		pinValidation();
		streetValidation();
		landmarkValidation();
		cityValidation();

		if (Object.values(validator).includes(false)) {
			e.preventDefault();
			setTimeout(function(){
				submitHandle.disabled = false;
			},100);
		}
		else{

		}
	}, false);


</script>

app/views/addresses/edit.html.erb
<h2>Update Address</h2>
<%= render 'form' %>

app/views/addresses/index.html.erb
<h2>Address List</h2>
<% if @addresses.empty? %>
	<p>No address found.</p>
<% else %>
	<ol>
		<% @addresses.each do |address| %>
		<li>
			Name: <%= address.name %><br/>
			Pin: <%= address.pincode %><br/>
			Street: <%= address.street %><br/>
			Landmark: <%= address.landmark %><br/>
			City: <%= address.city %> <br/>
			<%= link_to "Edit", edit_address_path(address.id) %> |
			<%= link_to "Delete", address_path(address.id), method: :delete, data: {confirm: "Are you sure you want to delete this address?"} %> |
			<%= link_to "Select", cart_line_items_path %>
		</li>
		<% end %>
	</ol>
<% end %>

<%= link_to "Add address", new_address_path %>

app/views/addresses/new.html.erb
<h2>Add Address</h2>
<%= render 'form' %>