config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'say/hello'
  get 'say/goodbye'
  root 'categories#index'
  #only for models we can use "resources", which finds all actions for the given controller
  resources :categories
  resources :products
  resources :reviews
  resources :cart_line_items
  resources :addresses
  resources :wishlists
  resources :orders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
has_many :reviews
belongs_to :category

has_many :cart_line_items

has_many :wishlists

has_many :order_line_items


validates_presence_of :name, :price, :description, :category_id, :cod_eligible, :feature_image_url
validates_numericality_of :price, minimum: 100
validates_numericality_of :category_id, greater_than_or_equal_to: 1

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	# load_and_authorize_resource 		#invokes ability class
	#path: products_path
	#url: localhost:3000/products
	#uri: /products
	#http method: GET
	#lists all products
	def index
		@products = Product.all
		@product = Product.new
	end

	#path: new_product_path
	#url: localhost:3000/products/new
	#uri: /products/new
	#http method: GET
	#creates new product
	def new
		@product = Product.new
	end

	#path: products_path
	#url: localhost:3000/products
	#uri: /products
	#http method: POST
	#takes the data in the form, passes it to the constructor as an argument, validate the object, if validations pass insert record into db and redirect the user to new page or display errors on the form page itself.
	def create
		@product = Product.new(params[:product].permit(:name, :description, :price, :category_id, :cod_eligible, :feature_image_url))
		respond_to do |format|
			if @product.save
				format.js
				# redirect_to product_path(@product.id), notice: "Product was successfully created!"
			else
				format.js
				# render action: 'new'
			end
		end
	end

	#path: product_path(id)
	#url: localhost:3000/products/:id
	#uri: /products/:id
	#http method: GET
	#fetches the product form the database and displays it on the show page, this page will be used to show all the the data about the product including associated info like reviews, QnA's, add product to the cart etc.
	def show
		@product = Product.find(params[:id])
		@review = Review.new
	end
	
	#path: edit_product_path(id)
	#url: localhost:3000/products/:id/edit
	#uri: /products/:id/edit
	#http method: GET
	#finds the record the user wishes to edit and display it on a form
	def edit
		@product = Product.find(params[:id])
	end

	#path: product_path(id)
	#url: localhost:3000/products/:id
	#uri: /products/:id
	#http method: PATCH
	#finds the record the user just updated in the browser and update its info by taking the data coming in from the form, validate the object.
	#if the validations pass, insert the record into the db and redirect the user to the product's new page,
	#else display the errors on the form
	def update
		@product = Product.find(params[:id])
		if @product.update_attributes(params[:product].permit(:name, :description, :price, :category_id, :cod_eligible, :feature_image_url))
			redirect_to product_path(@product.id), notice: "Product was successfully updated!!"
		else
			render action: 'edit'
		end
	end


	#path: product_path(id)
	#url: localhost:3000/products/:id
	#uri: /products/:id
	#http method: DELETE
	#find the record the user wants to delete, and destroy the record and redirect the user to new page
	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to products_path, notice: "Product was successfully deleted!"		
	end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_error.html.erb
<div class="alert alert-danger">
	<% if @product.errors.any? %>
		<h3>You form could not be saved because:</h3>
		<ul>
		<% @product.errors.full_messages.each do |msg| %>
			<li><%= msg %><br/></li>
		<% end %>
		</ul>
	<% end %>
</div>

app/views/products/_form.html.erb
<div id="error">
  
</div>
<%= form_for(@product, remote: true) do |f| %>

	<label for="product_category_id" class="form-group">Category: </label><br/>
	<%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Select Category"}, {class: "form-control"} %> <br/>

	<label for="product_name" class="form-group">Name: </label><br/>
	<%= f.text_field :name, placeholder: "Enter name", class: "form-control" %> <br/>

	<label for="product_description" class="form-group">Desription: </label><br/>
	<%= f.text_area :description, class: "form-control" %> <br/>

	<label for="product_price" class="form-group">Price: </label><br/>
	<%= f.number_field :price, min: 1, class: "form-control" %> <br/>

	<label for = “product_cod_eligible” class="form-group"> COD Eligible? </label><br/>
	<%= f.check_box :cod_eligible, class: "form-control" %>

	<label for = “product_image_url” class="form-group"> Image URL </label> <br/>
	<%= f.text_field :feature_image_url, class: "form-control" %> <br/>

	<%= f.submit "Add Product", class: "btn btn-primary" %>

<% end %>

app/views/products/_product.html.erb
<div class="col-md-3">
  <div class="card">
    <img class="card-img-top" src="<%= @product.feature_image_url %>">
    <div class="card-body">
      <h5 class="card-title"><%= link_to @product.name, product_path(@product.id) %></h5>
      <p class="card-text"><%= @product.description.truncate(200) %></p>
      <p class="card-text"><%= @product.price %></p>
      <%= link_to "Add to Cart", @product, class: "btn btn-primary" %>
      <% if user_signed_in? %>
        <%= form_for CartLineItem.new do |f| %>
          <label>Quantity </label>
          <%= f.select :quantity, (1..10).to_a %> <br/>
          <%= f.hidden_field :product_id, value: @product.id %>
          <%= f.submit 'Add' %>
        <% end %>
      <% else %>
        <p> You need to be logged in to add this product to your cart. </p>
      <% end %>
    </div>
    <div class="card-footer">
      <small class="text-muted">
        Found in: <%= Category.find(@product.category_id).name %>
      </small>
    </div>
  </div>
</div>

app/views/products/create.js.erb
<% if @product.errors.any? %>
  $('#error').html("<%= escape_javascript render 'error' %>");
<% else %>
  $('#error').hide();
  $('#newProduct').modal('hide');
  $.growl.notice({ message: "Successfully added the product!" });
  $('#productList').prepend("<%= escape_javascript render 'product' %>");
<% end %>

app/views/products/edit.html.erb
<h2>Edit Product(<%= @product.name %>)</h2>
<%= render 'form' %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-11">
    <h2>Listing Products(<%= @products.length %>)</h2>
  </div>
  <div class="col-md-1">
    <!-- Button trigger modal -->
    <% if (user_signed_in?) && (can? :create, Product.new) %>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newProduct">
        Add Product
      </button>
    <% end %>
    

    <!-- Modal -->
    <div class="modal fade" id="newProduct" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Add a new product:</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= render 'form', product: @product %>
          </div>
        </div>
      </div>
    </div>          
  </div>
</div>


<div class="row" id="productList">
  <% Product.all.each do |product| %>
    <div class="col-md-3">
      <div class="card">
        <img class="card-img-top" src="<%= product.feature_image_url %>">
        <div class="card-body">
          <h5 class="card-title"><%= link_to product.name, product_path(product.id) %></h5>
          <p class="card-text"><%= product.description.truncate(200) %></p>
          <p class="card-text"><%= product.price %></p>
          <%= link_to "Add to Cart", product, class: "btn btn-primary" %>
          <% if user_signed_in? %>
            <%= form_for CartLineItem.new do |f| %>
              <label>Quantity </label>
              <%= f.select :quantity, (1..10).to_a %> <br/>
              <%= f.hidden_field :product_id, value: @product.id %>
              <%= f.submit 'Add' %>
            <% end %>
          <% else %>
            <p> You need to be logged in to add this product to your cart. </p>
          <% end %>
        </div>
        <div class="card-footer">
          <small class="text-muted">
            Found in: <%= Category.find(product.category_id).name %>
          </small>
        </div>
      </div>
    </div>
  <% end %>
</div>


<!-- 
<%= link_to 'New product', new_product_path %> -->

app/views/products/new.html.erb
<h2>Add Product</h2>
<%= render 'form' %>

app/views/products/show.html.erb
<h2><%= @product.name %></h2>
<p> 
<% if (user_signed_in?) && (can? :update, @product) %>
<%= link_to "Edit", edit_product_path(@product.id) %> | 
<%= link_to "Delete", product_path(@product.id), method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>
</p>
<p>Price: <%= @product.price %></p>
<p>Description: <%= @product.description %></p>
<p>Category: <%= Category.find(@product.category_id).name %></p>
<% if @product.cod_eligible %>
	<p>COD Eligible</p><br/>
<% else %>
	<p>COD Not Eligible</p><br/>
<% end %>
<%= image_tag(@product.feature_image_url) %>



<h2> Add To Cart </h2>
<% if user_signed_in? %>
	<%= form_for CartLineItem.new do |f| %>
		<label>Quantity </label>
		<%= f.select :quantity, (1..10).to_a %> <br/>
		<%= f.hidden_field :product_id, value: @product.id %>
		<%= f.submit 'Add' %>
	<% end %>
<% else %>
	<p> You need to be logged in to add this product to your cart. </p>
<% end %>


	


<% if @product.reviews.empty? %>
	<p>No Reviews found, be the first to review</p>
<% else %>
<h3>Listing reviews</h3>
<ol id="reviewList">
	<% @product.reviews.each do |review| %>
		<li id="review_<%= review.id %>">
			Added By:<%= review.user.username %> <br/>
			Review:<%= review.body %><br/>
			Rating:<%= review.rating %><br/>
			<% if (user_signed_in?) && (can? :update, review) %>
			<%= link_to "Delete", review_path(review.id), method: :delete, data: {confirm: "Are you sure you want to delete this review?"}, remote: true %>
			<% end %>
		</li>
	<% end %>
</ol>
<% end %>



<p id="reviewNotice"></p>
<h3>Add your review</h3>

<div id="reviewError"></div>
<%= form_for(@review, remote: true) do |f| %>
	<label for="review_body">Body</label><br/>
	<%= f.text_area :body %> <br/>
	<%= f.hidden_field :product_id, value: @product.id %><br/>
	<label>Rating</label><br/>
	<%= f.radio_button :rating, 1 %> 1
	<%= f.radio_button :rating, 2 %> 2
	<%= f.radio_button :rating, 3 %> 3
	<%= f.radio_button :rating, 4 %> 4
	<%= f.radio_button :rating, 5 %> 5 <br/>
	<%= f.submit "Add Reviews" %>
<% end %>



<%= link_to "List Products", products_path %>