config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'say/hello'
  get 'say/goodbye'
  root 'categories#index'
  #only for models we can use "resources", which finds all actions for the given controller
  resources :categories
  resources :products
  resources :reviews
  resources :cart_line_items
  resources :addresses
  resources :wishlists
  resources :orders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  # Create, Read, Update, Destroy:
  # :create : new, create
  # :read : index, show
  # :update : edit, update
  # :destroy : destroy
  # :manage : all 7 above actions


  def initialize(user)
    if user.nil?
        can :read, [Category, Product]
    elsif user.role? "admin"
        can :manage, [Category, Product, Review]
    elsif user.role? "moderator"
        can :read, [Category, Product, Review]
        can :create, Review
        can :update, [Category,Product]
        can :destroy, Review
    elsif user.role? "customer"
        can :read, [Category, Product]
        can [:read, :create], Review
        can [:update, :destroy], Review do |review|
            review.user_id == user.id
        end
    end
  end



    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :user
	has_many :orders
	validates_presence_of :name, :pincode, :street, :landmark, :city, :user_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_line_item.rb
class CartLineItem < ApplicationRecord
	belongs_to :product
	belongs_to :user

	validates_presence_of :product_id, :user_id, :quantity

	#slim controller, fat model concept: all methoda should be detailed in the model side, and referenced to on the controller side.
	def save_or_update
		line_item = CartLineItem.find_by(user_id: self.user_id, product_id: self.product_id)
		if line_item.nil?
			self.save
		else
			line_item.update_attributes(quantity: line_item.quantity + self.quantity)
		end
	end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
	validates_presence_of :name
	validates_uniqueness_of :name
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	belongs_to :address
	has_many :order_line_items
	
	before_validation :set_default_values
	after_create :transfer_cartlineitems_to_orderlineitems
	after_create :empty_cartlineitems


	validates_presence_of :order_number, :order_date, :user_id, :total, :address_id

	def set_default_values
		self.order_number = "#{Random.rand(1000)}"
		self.order_date = Date.today
		self.total = calculate_total
	end

	def calculate_total
		total = 0
		self.user.cart_line_items.each do |cart_line_item|
			total += (cart_line_item.product.price * cart_line_item.quantity)
		end
		return total
	end

	def transfer_cartlineitems_to_orderlineitems
		self.user.cart_line_items.each do |cart_line_item|
			OrderLineItem.create(product_id: cart_line_item.product_id, price: cart_line_item.product.price, order_id: self.id, quantity: cart_line_item.quantity)
		end
	end

	def empty_cartlineitems
		# self.user.cart_line_items.each do |cart_line_item|
		# 	cart_line_item.destroy
		# end
		CartLineItem.delete(self.user.cart_line_items)

	end
end

app/models/order_line_item.rb
class OrderLineItem < ApplicationRecord
	belongs_to :order
	belongs_to :product
	validates_presence_of :product_id, :price, :order_id, :quantity
end

app/models/permission.rb
class Permission < ApplicationRecord
	belongs_to :user
	belongs_to :role
end

app/models/product.rb
class Product < ApplicationRecord
has_many :reviews
belongs_to :category

has_many :cart_line_items

has_many :wishlists

has_many :order_line_items


validates_presence_of :name, :price, :description, :category_id, :cod_eligible, :feature_image_url
validates_numericality_of :price, minimum: 100
validates_numericality_of :category_id, greater_than_or_equal_to: 1

end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :product
	belongs_to :user
	
	validates_presence_of :body, :product_id, :rating, :user_id
	validates_length_of :body, within: 10...1000
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :permissions
	has_many :users, through: :permissions

	validates_presence_of :name
	validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
	has_many :reviews

	has_many :permissions
	has_many :roles, through: :permissions

	has_many :cart_line_items

	has_many :addresses

	has_many :wishlists

	has_many :orders

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	validates_presence_of :username, :mobile
	validates_numericality_of :mobile
	validates_length_of :mobile, is: 10

	#whenever a user registers, by default he is a customer:
	#callback:
	after_create :assign_customer_role

	def assign_customer_role
		Permission.create(user_id: self.id, role_id: Role.last.id)
	end

	def role?(role)
		self.roles.pluck(:name).include?(role)
	end
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
	belongs_to :user
	has_many :products, through: :user
	validates_presence_of :product_id, :user_id
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Ecommerce</a><br/>
  <% if user_signed_in? %>
  <small>Welcome <%= current_user.username %>!</small>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

    <li class="nav-item">
      <%= link_to "Categories Page", categories_path, class: "nav-link" %>
    </li>

    <li class="nav-item">
      <%= link_to "Products Page", products_path, class: "nav-link" %>
    </li> 


    <% if user_signed_in? %>
    <li class="nav-item <%= controller.controller_name == 'cart_line_items' ? 'active' : '' %>">
        <%= link_to cart_line_items_path, class: "nav-link" do %>
          Your Cart <span class="badge badge-info"><%= current_user.cart_line_items.pluck(:quantity).inject(:+) %></span> ||
        <% end %>
      </li>

      <li class="nav-item <%= controller.controller_name == 'addresses' ? 'active' : '' %>">
        <%= link_to addresses_path, class: "nav-link" do %>
          Addresses <span class="badge badge-info"><%= current_user.addresses.count %></span> ||
        <% end %>
      </li>
      <li class="nav-item <%= controller.controller_name == 'reviews' ? 'active' : '' %>">
        <%= link_to reviews_path, class: "nav-link" do %>
          Reviews <span class="badge badge-info"><%= current_user.reviews.count %></span> ||
        <% end %>
      </li>

      <li class="nav-item <%= controller.controller_name == 'wishlists' ? 'active' : '' %>">
        <%= link_to wishlists_path, class: "nav-link" do %>
          Wishlists <span class="badge badge-info"><%= current_user.wishlists.count %></span> ||
        <% end %>
      </li>

      <li class="nav-item <%= controller.controller_name == 'orders' ? 'active' : '' %>">
        <%= link_to orders_path, class: "nav-link" do %>
          Orders <span class="badge badge-info"><%= current_user.orders.count %></span> ||
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to "Account Settings", edit_user_registration_path, class: "nav-link" %> 
      </li>

      <li class="nav-item">
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %> 
      </li>

    <% else %>
        <li class="nav-item">
          <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>

    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    <script src="/javascripts/jquery.growl.js"></script>
    <link href="/stylesheets/jquery.growl.css" rel="stylesheet" />



  </head>

  <body>
  <%= render '/layouts/nav' %><br/>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      
      <%= yield %>
      <%= notice %>
    </div>
    <!-- Footer -->
    <div class="mb-5"></div>
    <footer class="py-1 bg-dark fixed-bottom">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; My Ecommerce Application 2018</p>
      </div>
      <!-- /.container -->
    </footer>
  </body>
</html>